case: Get k8s not masked secret using get-k8s-resource tool
in:
  {
    "jsonrpc": "2.0",
    "method": "tools/call",
    "id": 2,
    "params":
      {
        "name": "get-k8s-resource",
        "arguments":
          {
            "context": "k3d-mcp-k8s-integration-test",
            "namespace": "test-secret-not-masked",
            "kind": "secret",
            "version": "v1",
            "name": "test-secret-not-masked",
          },
      },
  }
out:
  {
    "jsonrpc": "2.0",
    "id": 2,
    "result":
      {
        "content":
          [
            {
              "type": "text",
              "text": !!ere '{"apiVersion":"v1","data":{"bar":"UHNzdCBkb24ndCB0ZWxsIGFueW9uZQ==","foo":"VGhpcyBpcyB2ZXJ5IHNlY3JldCE="},"kind":"Secret","metadata":{/.*/"name":"test-secret-not-masked"/.*/',
            },
          ],
        "isError": false,
      },
  }
