case: Get k8s secret using get-k8s-resources tool
in:
  {
    "jsonrpc": "2.0",
    "method": "tools/call",
    "id": 2,
    "params":
      {
        "name": "get-k8s-resource",
        "arguments":
          {
            "context": "k3d-mcp-k8s-integration-test",
            "namespace": "test-secret",
            "kind": "secret",
            "version": "v1",
            "name": "test-secret",
          },
      },
  }
out:
  {
    "jsonrpc": "2.0",
    "id": 2,
    "result":
      {
        "content":
          [
            {
              "type": "text",
              # Values would be masked by default, unless explicitly disabled with `--mask-secrets=false`
              # , last-applied-configuration annotation must be dropped too
              # The pattern here is made more precise to avoid missing not masked fields
              "text": !!ere '{"apiVersion":"v1","data":{"bar":"MASKED","foo":"MASKED"},"kind":"Secret","metadata":{"annotations":{},"creationTimestamp":"/[^"]*/","name":"test-secret","namespace":"test-secret","resourceVersion":"/[^"]*/","uid":"/[^"]*/"},"type":"Opaque"}',
            },
          ],
        "isError": false,
      },
  }
